### PR TITLE
update ko.json

### PR DESCRIPTION
**Pull request by mmega**
ko translation update please

### CODE REVIEW

**Comment by mmega** [comment]
Found at 225
225    "focusOnFile": "Focus on file search inptut", 
input? inptut?

**Comment by whyboris** [comment]
Should be `input` -- I'll fix now

**Comment by mmega** [comment]
thanks!

**Comment by whyboris** [comment]
Thank you for the translation and for catching the misspelling 😅 fixed with https://github.com/whyboris/Video-Hub-App/commit/d4ed3040b2b444c7595486a5ba694dfbd7015092

I fixed it in all the files, but I suspect I should re-translate this line in all other languages at some point later 😅

**Pull request merged**
