### PR TITLE
Filter down the Tag Tray based on videos #436

### PR DESCRIPTION
**Pull request by martincaron**
Solves Issue #436 

Follows the same logic as the Word Cloud.

### CODE REVIEW

**Comment by whyboris** [comment]
Really cool! The code looks great. I'll run this sometime to see how it works 🤝 

Thank you for your contribution 🙇

**Comment by martincaron** [comment]
No problem! As a side note, and probably part of a different discussion :

As I was digesting the code for the `Tag Tray` and also the `Word Cloud`, I couldn't help notice how similar the functionality is and how we have a bit of duplicate code going on there. What would you think about merging the `Word Cloud` into the `Tag Tray` as some sort of toggle ?

It could potentially be treated as 1 of 2 views within the Tag Tray. (User's choice.) : 
1. The weighted Word Cloud view
2. or the current pills view

**The positive potential :**
- streamline all UI/UX for tags under one spot. clean.
- clean up some duplicate code
- consolidate some settings 
- easily introduce auto-tags in the Tag-Tray
- Color code the tags based on type (like in details view)

**What we'd have to watch out for :** 
- Users who use both wouldn't have them simultaneously anymore. (would have to toggle back and forth_
- Batching and drag-dropping with Word Cloud could be a little tricky ?

This all being fresh still, I'd have a pretty good idea on how to go about it but would need some help on UX/UI.

Interested on your take.

**Comment by martincaron** [comment]
We could also achieve some of those improvements independently from merging the Word Cloud into the Tag Tray as well.

Anyways, If you prefer discussing it outside the PR , I can open up an issue for this.

**Comment by whyboris** [comment]
I like the idea of having the word cloud in the tag tray.

There is very little space in the sidebar when compared to the tag tray, and the words in the cloud get very small, to the point of non-readability 😅 

The word cloud was originally designed before any tags came around (possible reason for duplicate code you mention). 

I'm still unsure who uses the word cloud, but if they do, they probably would like seeing a more-readable list in the horizontal tray 🤷 

I'm open to a PR that merges things. I'll likely clean up the UI after it merges (so feel free to leave the UI part to me) 👍

**Comment by whyboris** [comment]
Sorry I still haven't responded to your comment: https://github.com/whyboris/Video-Hub-App/issues/403#issuecomment-629664020

😓  -- I like your proposal in that comment -- try to be consistent, using tags across the board.

So the `tag` tray would be in two modes: "word cloud" or "manual tags" ? Or would it be possible to toggle to show a mix of both?

I wonder if it would be simple to hook into the auto-tags and also show those in a third mode?

I'm open to anything really -- I'm thinking of the next release being version 3 (with multi-source-folder-support and more) so we could have quite a redesign along the way.

Please feel free to open an issue for a discussion (you can copy-paste your comment from above, and link [your other comment](https://github.com/whyboris/Video-Hub-App/issues/403#issuecomment-629664020) as well).

🤝

**Comment by martincaron** [comment]
Thanks for the feedback @whyboris . I'll open up an issue for further discussion here : #442 

Keeping this PR for it's original intent.

**Comment by martincaron** [comment]
Found a bug on this :

It only functions if the Word Cloud is enabled.  👎 

Will provide a fix.

**Comment by whyboris** [comment]
Hello 👋 

I've changed the primary branch name from `master` to `main` and changed the PR to be against `main` 👍 
I have merged in a huge PR with the VHA `3.0.0` work into this branch 😅 
Surprisingly there were no merge conflicts despite the number of changes 😁 

Please let me know if you wanted to do anything else with your PR -- otherwise I'll just merge it in and fix up whatever is left myself 🤝 

Thank you again for your excellent contribution 🙇

**Comment by whyboris** [comment]
Hey @martincaron 

I recently unified the `word cloud`, `similar videos`, and `tags` into a single tray on the bottom (and added a `recently played` as well) with #553 

Please let me know if you'd like to get your PR into release, or if you'd like me to take over and reconcile the conflicts myself 👌 

No rush -- I think I'm at least a month away from finishing the `3.0.0` release 🤝

**Comment by whyboris** [comment]
@martincaron -- I'm wondering if this feature is now obsolete, please see comment: https://github.com/whyboris/Video-Hub-App/issues/436#issuecomment-737379400

😓 sorry to have you do all this work and it might not even make it into the app 🙇 

Please let me know what you think 🤝 I'm open to a discussion on this 👍

**Comment by whyboris** [comment]
@martincaron -- please let me know if you think it's ok to close this PR 😓

**Comment by whyboris** [comment]
Thank you very much for your work 🙇 
Sorry this code didn't get into the final project, but I think the functionality you intended has already arrived 🤞 
I'm happy to reopen this PR 👌 if you think this adds something that's missing from the app 🤝 just let me know 😁

**Pull request closed without merging**
