### PR TITLE
Add translation process automation

### PR DESCRIPTION
**Pull request by Lakshamana**
Refers to: #194.
Please, review.

### CODE REVIEW

**Comment by whyboris** [comment]
Thank you for this awesome contribution -- I'll test it out within a day or two and likely merge as is 👍

**Comment by Lakshamana** [comment]
@whyboris, I'm using Manjaro Linux. I'll start to test your OS X solution for sed. For sake of portability, it could be handy to add a function to get system's label (bash's `uname`* command). Thanks for reviewing!

**Comment by whyboris** [comment]
I already tried my solution on a Mac -- it worked :)
I think it's just worth seeing if including the `""` still works on Linus -- if it does, we may as well merge it in 👌 

I always feel uneasy whenever I request any edits to a PR -- a person (you in this case) have already done some awesome work, and to request more feels like in poor taste 😅 

I'm happy to merge the feature as is too -- no pressure to do more work 🙇 🙇 🙇

**Comment by Lakshamana** [comment]
Hey, @whyboris, I just added a function to check whether it is running on a Mac or Linux (and could be added more OS cases). If it's a Linux, use Linux's `sed` otherwise it will use Mac's one

**Comment by whyboris** [comment]
I'm unsure what the problem with _Mac_ is -- but the script generates new files on my machine:
```
        "../components/common/app-state.ts\"\""
        "../components/home/home.component.html\"\""
        "../components/home/home.component.ts\"\""
```
Note the `\"\""` at the end. The files look like what we want, but the stuff at the end is likely some other OS X bug 😞 

ps - the OS detection code is in the first block, but the other `sed` commands would need the same treatment. Perhaps this would be easier? Use your code somewhere above to define a new variable:
```
get_os
if [ $result = 'linux' ]; then
  SED_HACK=''
elif [ $result = 'osx' ]; then
  SED_HACK='""'
else
  echo 'System not supported'
  exit 1
fi
```
Now insert the `SED_HACK` into the command, e.g.
```
sed -i $SED_HACK "/export type SupportedLanguage/ s/;$/ | '$NEW_LANG_CODE';/" ../components/common/app-state.ts
```
So on _Linux_ this hack would insert an empty string, not causing trouble, while on _Mac_ we'll have the desired `""` 🤔

**Comment by cal2195** [comment]
Automation++ 😄 

I wonder if this would be easier if we had a separate file for the LANG_CODES, and dynamically populated them at runtime in each location, so we only need to edit one file?

Also, this won't run on Windows by default, which is why I used node for the original script. not sure if that's an issue or not? 🤔 

Great work @Lakshamana 👍

**Comment by Lakshamana** [comment]
> ```
> get_os
> if [ $result = 'linux' ]; then
>   SED_HACK=''
> elif [ $result = 'osx' ]; then
>   SED_HACK='""'
> else
>   echo 'System not supported'
>   exit 1
> fi
> ```
> 
> Now insert the `SED_HACK` into the command, e.g.
> 
> ```
> sed -i $SED_HACK "/export type SupportedLanguage/ s/;$/ | '$NEW_LANG_CODE';/" ../components/common/app-state.ts
> ```
@whyboris, yeah, that approach would be easier. I was thinking in such a way to do this but didn't figure out a way to do this properly.

**Comment by Lakshamana** [comment]
Thanks, @cal2195. If you prefer I could migrate my code to node. However, Windows 10 can run bash, though it is a beta feature (and it's not a native windows application). Since I don't use windows at all, I don't know if all bash commands are available for it to use.

**Comment by cal2195** [comment]
@Lakshamana If this is working, I'd say merge as is for now! Just something we could do in the future, especially if we wanted to add more automation to this/other tasks! 😄 

WSL is certainly good, and should basically appear as a Linux system, but if you're doing VHA dev on Windows, you already have node, so it's one less thing to get installed! 😅

**Comment by Lakshamana** [comment]
@cal2195, totally agree on dev dependencies for improving dev experience. This works in my machine. So it's ready to merge (for now, I'm just waiting for tests in OS X).

**Comment by whyboris** [comment]
This worked beautifully on my _Windows_ machine ✅ 
On _Mac_ it still created 3 new files rather than update the old ones (see https://github.com/whyboris/Video-Hub-App/pull/195#issuecomment-509895401).
I'll merge as is -- it's probably just a few characters away from perfect and I'll get it to work and patch it in the near future 🤝 

Thank you again for your work @Lakshamana and thank you for joining in @cal2195 🙇

**Pull request merged**
