### PR TITLE
Nicer looking tooltips

### PR DESCRIPTION
**Pull request by cal2195**
Little change to the tool tips to allow for longer text, and make them look a little nicer! 👍 

Will follow up soon with more tooltips for the more complicated features!

### CODE REVIEW

**Comment by whyboris** [comment]
It really is a matter of taste ...

Yours:
image

Mine:
image

Downside of mine is long text might begin to overflow (especially when the app width is small). Though I see it as a benefit of mine that the hint text is harmonious with the rest of the text (same style).

I would prefer to stay with my current implementation 🙇

**Comment by whyboris** [comment]
I'm not really insisting on keeping the tooltip I currently have ... maybe if you share some of your thoughts on why a tooltip with a box may be better I might change my mind? :)

**Comment by cal2195** [comment]
I agree that the style isn't very good - I think I was having some strange transparency/overlap issues - I actually wanted it to appear below, and even shift down the other buttons, but I couldn't get it to work! 😢 

Ideally, I just want to make it really easy to see what's help text - I think the current implementation is too hard to read when the text gets long, and the help text should be verbose to explain in detail each feature...

**Comment by whyboris** [comment]
@cal2195 -- I'm aiming to close out tickets / PRs as we near the 2.0.0 release (few weeks from now earliest).

No rush on this -- just let me know sometime if I should reconsider the current tooltip -- perhaps to create a hybrid of the two.

I'm pretty good at CSS -- so you could sketch in Photoshop / some other editor what you have in mind (or a screenshot of some tooltip you like) rather than having to get into CSS yourself 😉

**Comment by whyboris** [comment]
@cal2195 -- just let me know if you'd like me to re-open this PR 👌 (or re-open it yourself if you have the repository permissions 👍 )

Closing as I'm cleaning up before `2.0.0` release 🚀

**Pull request closed without merging**
