### PR TITLE
Fix Issue #726 - Adding a "folder does not have filter"

### PR DESCRIPTION
**Pull request by rokaicker**
Hi!

I think I've got the new feature working ([Issue 726](https://github.com/whyboris/Video-Hub-App/issues/726)). Please let me know if there are any changes to be made. 

Also, would it be okay to tag this for hacktoberfest?

By the way, your code base is amazingly organized and incredibly modular, and I learned a lot just by navigating through the filter workflow.

### CODE REVIEW

**Comment by whyboris** [comment]
Thank you for the contribution! 🙇 
I'll try to find time this weekend to test it locally 🤝 
From my glance at the code - it looks good! 😁

**Comment by rokaicker** [comment]
Learned about git rebase this week, so I thought it would be best for cleanliness if I combined all my commits into a single one.

**Comment by whyboris** [comment]
I'm a big fan of `Squash and merge` - so whenever I merge a PR, no matter how many commits it contains, the resulting merge shows 1 commit with the PR number. This makes the commit history very clean 😎

**Comment by rokaicker** [comment]
> 

Ooo! I didn't know that was possible, that also seems like a very useful tool from a maintainer perspective! I'm still learning so many new things about git, thanks!

**Comment by whyboris** [comment]
Thank you @rokaicker for your PR 🙇

**Pull request merged**
