### PR TITLE
Update Electron to 5.0.1

### PR DESCRIPTION
**Pull request by whyboris**
And update as many dependencies as I can without breaking 🙆‍♂ 

It's unclear if we need `node-sass` -- we were fine beforehand, but that could have been because it was implicitly included with _Angular-CLI_ ... but as I was jumping around to _Node 12_ it seemed to have messed things up. There's little harm in having an extra _devDependency_ 👌

### CODE REVIEW

**Comment by whyboris** [comment]
Update all the versions of dependencies (other than Angular) that can be updated without breaking ✅ 

We'll update to Angular 8 once it comes out 👍 -- it might make it easier to update to Electron 5 👍 and might solve the problems with updating `zone.js` and `core-js` 😅

**Comment by whyboris** [comment]
Confirming I'm able to run this branch with _Node 12_ :tada:

I recommend using `nvm` to switch versions (rather than install a new node version globally -- just in case). 

Might require running `npm rebuild node-sass` after switching to Node 12 👌

**Comment by whyboris** [comment]
🎉 Was able to update to `Electron 5.0.1` thanks to this:

https://stackoverflow.com/questions/55093700/electron-5-0-0-uncaught-referenceerror-require-is-not-defined

**Comment by cal2195** [comment]
This looks great! I'll try it out now! 👍

**Pull request merged**
