### PR TITLE
Modal instead of system message

### PR DESCRIPTION
**Pull request by whyboris**
Thank you to @orkomlosh for setting this up 🎉 

Creating a PR so it's easier to test current changes 🤝

### CODE REVIEW

**Comment by whyboris** [comment]
Hey @orkomlosh -- I'm puzzled but I can't get it to work 😓 

I see the modal is added through `<div class="cdk-overlay-container">` which gets appended to the bottom, but it doesn't show up visually, and there are these annoying scroll bars on the side and bottom of the app 😕 

Is there something else I need to do to get it to look like your screenshot?

**Comment by whyboris** [comment]
As a side-note, the CDK creates a humorously-deep nested thingy :trollface: 
image

I already have an "overlay" that can detect clicks -- it wouldn't be too hard to just add a custom modal of our own and be done with it 🤔 

I'm happy to give the CDK another try -- but as of now I can't get it to show anything 😓

**Comment by orkomlosh** [comment]
yeah it something that comes with the mat-dialog i guess.
i'm not sure why it's happening.
let me take another round on this. and if i cant fix this. i'll try to use regular modal, and we will kick the mat-dialog out!
thanks for the help, and sorry for wasting your time 😢

**Comment by whyboris** [comment]
You didn't waste my time! 👌 
Thank you for trying this out -- I was just surprised why I couldn't get the dialog to show up (even though I see the message in the DOM).

**Comment by whyboris** [comment]
🎉 found it!
`@import '~@angular/cdk/overlay-prebuilt.css';`
was missing the CSS: https://material.angular.io/cdk/overlay/overview#initial-setup

**Comment by whyboris** [comment]
I added CSS to it too:

`styles.scss`:
```css
@import '~@angular/cdk/overlay-prebuilt.css';

.mat-dialog-container {
  background-color: white;
  border: 1px solid gray;
  border-radius: 8px;
  box-shadow: 0 10px 20px 10px rgba(0,0,0,0.1);
}

```

image

**Comment by whyboris** [comment]
One reason reason you may have had with nothing shows up is because I have a hack `reduceFlicker` overlay - something that might be obsolete now 🤔 -- or maybe not -- it's something I put in for a beautiful fade-in into the app the first time it starts 😁

**Comment by whyboris** [comment]
Merged so that I could add my touches to it 😎 with #503

**Pull request merged**
