### PR TITLE
Adding compact view option also for filmstrip view

### PR DESCRIPTION
**Pull request by semla**
As per issue #684

### CODE REVIEW

**Comment by whyboris** [comment]
Thank you @semla -- the code looks great! I'll test it out to see how it looks in the GUI and will try to merge it in soon.
It might be a few weeks as I'm a bit busy with house stuff still.
Cheers 🙌

**Review by whyboris — COMMENTED** [review]
It's looking great in the UI as well 👍 

I'm happy to adjust the code myself after the merge, but please let me know if you'd like to fix a few minor things:

- there is now a horizontal scrollbar on the bottom (for some reason I think the filmstrip is wider than the view 🤔 )
- when compact mode is toggled, the filename is still showing up behind the filmstrip (and can be seen a bit to the left)

No worries if you'd rather not mess with it -- I'll happily merge this in and fix it myself -- later this winter when I'm back to coding on the app.

**Comment by semla** [comment]
Glad to hear it is looking good!
Busy at the moment and it has been a while since I saw the code so I think I leave the fixes for you.
Cheers

**Comment by whyboris** [comment]
Thank you for the quick response 🤝 I'll fix up the minor edge case -- I appreciate the addition 🙇 

Maybe this weekend 🤞

**Comment by whyboris** [comment]
I'm hoping to have a release at the end of February 😓 -- this year has been busier than I ever anticipated.

**Comment by whyboris** [comment]
I have a guess why there was some need for `css` improvement 😅  -- in the code (template) you instruct the app to use a class called `compact-margins` but it isn't part of the PR 👌 

I'll merge in and fix in _main_

Thank you again for the contribution 🙇 

This will be a part of the _5th Anniversary Release_ today 🥳

**Comment by whyboris** [comment]
🙇  thank you @semla for your contribution -- I made a small fix with this commit: https://github.com/whyboris/Video-Hub-App/commit/09c57b8fdf4a577d258376bf17dc64953cda5581

Looks beautiful ❤️

**Pull request merged**
