### PR TITLE
Save sorting option! :)

### PR DESCRIPTION
**Pull request by cal2195**
Just a small change, to save the selected sorting option on exit, and reload it on open! :)

Let me know if you'd save/load the option anywhere else! 😄

### CODE REVIEW

**Comment by whyboris** [comment]
Pretty cool improvement! I suspect some people will have a preference for viewing their files in some other order by default on launch.

There is at least one bug:
```
Uncaught TypeError: Cannot read property 'nativeElement' of undefined
```

Happens if you select a sort option, then close the sorting setting (click on `Sort order` button -- 4th one in the "Filters & Sorting Options") and close the app, and then re-open the app.

I think it's a neat feature to have -- we should just catch when the element exists 😉

**Comment by whyboris** [comment]
Hey @cal2195 -- I'm thinking I might release the app this weekend ... this _might_ not make it to 2.0.0 and might go out with a patch or a minor version update.

Do let me know if you don't have time and would like me to fix the minor bug I found with your code prior to release 👌

**Comment by cal2195** [comment]
I'm on PTO, so feel free to fix the bug, or leave it for a patch! 😄

**Comment by cal2195** [comment]
Fixed the bug! 👍 🐛

**Comment by whyboris** [comment]
Sorry for delaying the review for so long -- I'll surely get to it this weekend 😅 
Sorry I merged a few PRs first, so there's also a merge conflict. Please let me know if you'd like me to resolve it 🤝

**Comment by cal2195** [comment]
Merge conflict addressed! 👍

**Comment by cal2195** [comment]
bump 😄

**Comment by whyboris** [comment]
Sorry still haven't touched VHA code in 2 weeks 😓 
Will definitely merge this by the end of the weekend 👌 

ps: 😁 
- Finally released https://github.com/whyboris/Health-Impact-Fund 
- Trying to find time to work on https://github.com/whyboris/Simplest-File-Renamer

**Comment by whyboris** [comment]
Thank you again for your continued improvements to _Video Hub App_ 🙇

**Pull request merged**
