### PR TITLE
Fix various path issues

### PR DESCRIPTION
**Pull request by whyboris**
There are some lingering path issues:
- https://github.com/whyboris/Video-Hub-App/issues/249#issuecomment-519979659
- thumbnails broken when hub name has a space in it
- etc 🤷‍♂ 

Hoping to fix them all 😅 

note: _clip view_ changes are mostly indentation ⚠️ 

PR adds a path service to standardize how paths are generated in all views 👍

### CODE REVIEW

**Comment by whyboris** [comment]
I doubt I fixed the issue in https://github.com/whyboris/Video-Hub-App/issues/249#issuecomment-519979659
But this PR may make it easier to debug for @theotherp -- so I'm merging this to _master_ to see if issue persists 😅

**Comment by whyboris** [comment]
@cal2195 -- no action needed from you -- just noting so you're not surprised some day:

I updated some of the code you've written -- the template `clip.component.html` had several elements that repeated; I put them together into `*ngFor` making the document easier to read 👍 

Thank you again for your work on clips -- everything is still working smoothly 🙇

**Comment by cal2195** [comment]
Haha, I always review everything eventually! 😂 
This looks great! Did it sort out the issue?

**Comment by whyboris** [comment]
I think there may be some weird edge cases (I've not yet replicated on Mac or Windows) - but I'll follow up with the original thread in #249

**Pull request merged**
