### PR TITLE
Fix to remove black at end of filmstrip preview!

### PR DESCRIPTION
**Pull request by cal2195**
This PR fixes one of the filmstrip bugs in #50 - it removes the black at the end of a filmstrip! 🎉

### CODE REVIEW

**Comment by whyboris** [comment]
I'll try it out later this week 👍

**Comment by cal2195** [comment]
An alternative is, along with #71, we could have the filmstrip only show an integer number of screenshots with no cut off - what do you think of this? 💡

**Comment by cal2195** [comment]
I've implemented my last comment in #170! 👍

**Comment by cal2195** [comment]
This has been fixed in #170 - Closing! 🎉

**Pull request closed without merging**
