### PR TITLE
Quick file rename

### LINKED ISSUE #400: Quick file rename
I have the following feature request:
Please implement a very fast file rename: make the filename in the view editable: a click on the filename in the view places a cursor and you can immediately stark typing and on changing the focus (e.g. by clicking elsewhere or pressing ENTER or TAB) the file is renamed.
Like if it would be an input-box with no visible border and transparent background.
This would speed up the workflow when importing new videos.

### PR DESCRIPTION
**Pull request by byrw**
Fixes #400

### CODE REVIEW

**Comment by whyboris** [comment]
Awesome! Thank you for your work 🙇 

Exciting! a new component 😀 -- I'll test the code soon 🤝

**Comment by whyboris** [comment]
Thank you again for your contribution! It functions well in the _Details view_ and is easy to use 🏅

It does change the styling significantly in the _Rename_ popup and it's a little rough around the edges inside the _Details view_. I don't mind -- I can fix it up after I merge 👌 

Please let me know if you'd like to spend any more time on this PR -- whether you'd like to polish up the CSS / layout, or you'd rather I handle it 🤝 

Cheers!

**Comment by byrw** [comment]
@whyboris and now? what do you think? I not pretty sure how you want to look like, so i think its better if you style it.

**Comment by whyboris** [comment]
Thank you -- I'll merge your PR in sometime today or over the weekend.

Please take no offense if I change the code a bit. The styling specifically -- I may have some strong preferences about some aesthetics 😅 🙇 

I might replace the "rename file" with a small pencil icon next to the title ... and now that I'm thinking about it -- I want to make the title in the _Details view_ larger too 🤔 (different from how it always looked 🤷 )

Cheers 🎉

**Comment by whyboris** [comment]
Thank you @byrw -- I'm merging this PR into a branch called `renaming-file-integration`
I will create, based off it, a new branch `renaming-styling` and work on the few minor CSS fixes I'd like to include. 
Then I will merge the `renaming-styling` fixes into the _integration_ branch and then merge the _integration_ branch into _master_ 😅 

It might take me up to a week to work on this (not because it's a lot of work but because I'm spreading myself thin across the many things I want to do 😜 )

**Comment by whyboris** [comment]
I'll add the styling sometime this week: https://github.com/whyboris/Video-Hub-App/pull/407

**Pull request merged**
