### PR TITLE
create image-element.service to replace final arr

### PR DESCRIPTION
**Pull request by orkomlosh**
@whyboris I tried to create the service for imageElement, (as discussed here https://github.com/whyboris/Video-Hub-App/issues/456#issuecomment-674533251)
let me know if that what you meant, 
and please offer a new name for the service because i failed to find one. 😆

### CODE REVIEW

**Comment by whyboris** [comment]
I think this is exactly what I had in mind 😁 

I'm not 100% sure about all the benefits of doing things this way (having a dedicated service as you added), but it feels like it's a step in the right direction. I suspect after this change, some of the methods from `home.component` could (eventually) be moved there (though I'm unsure 😅 ) 

Please let me know your thoughts (if any) on all this 🤝

**Comment by orkomlosh** [comment]
I added it as a dedicated service since it's not really a component right? I mean it doesn't have template at all.
And yeah i guess that now we can probably start moving methods that can be used all over the application to the service.

**Comment by whyboris** [comment]
ps - would you like to be a "collaborator" on this repository?

This would give you a bunch of [administrative privileges](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account).

It's not that I want you to edit others' comments or merge pull requests -- it's more about welcoming you as an ongoing collaborator on the project 🤷‍♂️ -- you'd have no extra obligations 🤝 

No pressure -- just an offer 👍

**Comment by whyboris** [comment]
Yeah -- a dedicated service is exactly what I had in mind. In Angular it's a "singleton" so it's just what we want -- a single copy of `ImageElement[]` and it's a way to swiftly interact with the data inside (whenever needed). 

Initially, before the `3.0.0` refactor, like 90% of the code :trollface: was in `home.component` (and most of app code is there still 😅 ) ... it feels like breaking out code into meaningful sections is a worthwhile task for making it easier to add features, edit features, and avoid bugs 🤞

**Comment by orkomlosh** [comment]
> ps - would you like to be a "collaborator" on this repository?
> 
> This would give you a bunch of [administrative privileges](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account).
> 
> It's not that I want you to edit others' comments or merge pull requests -- it's more about welcoming you as an ongoing collaborator on the project 🤷‍♂️ -- you'd have no extra obligations 🤝 
> 
> No pressure -- just an offer 👍 

Wow, of course, it will be great. I really enjoying contributing this library!

**Comment by orkomlosh** [comment]
So I started 1 level of change to home component and I gathered all the emissions to 1 handle emission in the service. next step we can remove the emitting chain from the lower to the top by just using the service. 
it's a bigger change to do it. we can do it in baby steps. your decision.

**Comment by whyboris** [comment]
I'm excited about this change now -- with your changes in place I see more-clearly how straight-forward it is to move the emits out 😁 

I'm happy to jump in on the refactoring this thing -- or feel free to call dibs on the next step 🤝 

If you choose to keep going with the refactor, feel free to continue in this branch, or create a new branch off this work and create a new PR to land on top of this one, or if you prefer you can merge this PR to `main` ✅

**Comment by orkomlosh** [comment]
so I'll merge this first in order to not have long timed PR's and branches.
After that i'll get to the child components to try and change the way it treats finalArray updates (using the service from now on).

**Pull request merged**
