### PR TITLE
lately added features (offline filter) updated in Czech translation

### PR DESCRIPTION
**Pull request by lighthunt**

### CODE REVIEW

**Comment by whyboris** [comment]
Thank you for the updates 🎉 🙇 

There might be some more minor additions / changes to the language leading up to `3.0.0` release 😅

**Comment by lighthunt** [comment]
> There might be some more minor additions / changes to the language leading up to `3.0.0` release 😅

@whyboris yes I realize that happens over time for all translations. how do you solve this btw, do you notify/ask people who did translation originally for major updates?

(As for me I was using czech version intentionally just to see if I spot issue and found english leftovers in the app, realized missing some keys - by comparing the source, which I believe is en.json).

For the Czech version, I'll try to update before release, when I have time, feel free to notify me.

---
And BTW, my assistant is currently working on Vietnamese translation (VN is actually a big market ... ). I'll see if I can add in about a week time.

**Comment by whyboris** [comment]
Almost all the translations are have are machine translations (Google Translate 😅 ) - so they aren't very good. But I am fluent in Russian, I glanced and the translations, and they aren't bad either 🤷‍♂️ 😅 

A few people improved translations; I think you're the first to add a new language 🙇 

Thank you for your continued help 😁 🤝 😄 

Vietnamese translation is very welcome too 🙇 

The languages I auto-translated were the most-spoken languages in the world, though I may have missed one or two.

**Comment by lighthunt** [comment]
@whyboris  So I guess your "add translation" readme/tutorial finally paid off. especially the part how to integrate new translation, which would take me a lot of trial and error before I would be able to build and verify it if it wasn't there. VN version is coming soon

**Comment by lighthunt** [comment]
@whyboris BTW why don't you advertise multi langauge support on the home website? Plus the website should be mutli language as well and indexed by search engines, to get users (and antimalaria support)....

**Comment by whyboris** [comment]
Thanks for the suggestion -- the website is about 3 years old now (even the screenshots are from version `1.0.0` 😅 )

I'm planning on rewriting it in _Gatsby_ with multi-language support (as you suggest).

Current website GitHub: https://github.com/whyboris/video-hub-app-public-website

I've already built a multi-language website before:
https://healthimpactfund.org/
https://github.com/whyboris/health-impact-fund

I have a week vacation coming up in one week -- hope to get some VHA work done 💪

**Pull request merged**
