### PR TITLE
hide donut when ribbon is collapsed

### PR DESCRIPTION
**Pull request by orkomlosh**
@whyboris I got your comment very seriously: https://github.com/whyboris/Video-Hub-App/issues/355#issuecomment-671490094
the donut in this PR  will collapse with the top bar. works like charm.
if you want to do something else with the donut let me know.

### CODE REVIEW

**Comment by whyboris** [comment]
Thanks for the solution!

Hiding the doughnut progress bar isn't hard as you noticed ... my (unstated) worries were about how to communicate to the user that something is happening -- that we're still extracting things.

I've added a new indicator (green pulsating icon) next to the total number of files counter on the top of the sidebar (to indicate that we're scanning a folder for files) ... I think I'll add the same indicator to show we're extracting thumbnails (on top-right where the doughnut was) to indicate we're extracting screenshots 👍 

Let me know if you'd like to add the green icon yourself (see the `div` with `scanning-indicator` class) 🟢  -- else I'll merge in your PR and add it myself 👌 🤝 😁

**Comment by orkomlosh** [comment]
ok, I'll take a look on this tomorrow,
BTW i noticed the the application header is also printing the the percentage and that it's indicating about the scan.

**Comment by whyboris** [comment]
You're right! I forgot about that. It may be enough 🤔 

No rush on anything you do with VHA! All help is appreciated 👐

image
Seems like it could be nice to have.

ps - the taskbar should also already be indicating screenshot extraction progress 😎

**Comment by orkomlosh** [comment]
So i tried to implement it and i manage to do something,
but i must admit i'm not very good with CSS, aligning and positioning objects.
(my background is mostly from .net)
so it's not pixel perfect: 😄 
image
 and i'm not sure what the right way to do it.
please correct me.

**Comment by whyboris** [comment]
Super awesome! Thank you for the clean work 🙇 
I'll nudge the icon a few pixels with some CSS 👌

**Comment by whyboris** [comment]
I nudged the icon a bit with this commit: https://github.com/whyboris/Video-Hub-App/pull/499/commits/1118d143475b9c9b877295a4a72fbddf56799daa
Also removed the container that was no longer needed (as I used `position: absolute`: https://github.com/whyboris/Video-Hub-App/pull/499/commits/9e4394b1bfb9e80d12add33c82d2dd9eb8a02187

It's hacks everywhere 😅 -- the right-padding on the `.all-settings` class is what makes the buttons start disappearing on the right as they get too close (and are about to overlap with the settings button and the newly-added indicator) 😆

**Comment by orkomlosh** [comment]
Great, thx for the detailed explanation

**Pull request merged**
