### PR TITLE
Convert vha files to zip files!

### PR DESCRIPTION
**Pull request by cal2195**
This is a precursor to #29 - it now saves vha files as zip files, and loads them in correctly!

As a bonus, we could also store other data in this zip file! 💡 

I haven't looked into optimal compression settings yet, but that can be improved! 👍

### CODE REVIEW

**Comment by whyboris** [comment]
Looks clean - I'll try it out within this hour and merge if it runs without issue 👍

**Comment by whyboris** [comment]
Of course this branch would be a super-breaking change for old files. That's not too much of a problem since users will have to re-import their screenshots anyway. But with this change, at the moment, users won't be able to pen any of their old files either - an error would occur.

At the moment I get this error: 
>UnhandledPromiseRejectionWarning: Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
> Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Sadly it breaks the app in a way that it doesn't even go to the _Wizard_ menu to start a new hub.

**Comment by whyboris** [comment]
It looks like it's possible to catch the error and re-use the old method of parsing the file ... but it may add more complexity. It's maybe OK to just declare 0 backwards compatibility with older `vha` files going forward (and I could have a tiny write-up for what people can do to manually move the _auto-tags_ if they have any).

I'm also wondering if without the compression the .vha files will be _that_ large -- you said you have tried a video directory with ~10,000 files. I'm guessing the `.vha` is under 10mb. 

So we _could_ just not compress the file in the end - saving some coding complexity and not requiring another dependency 😅

**Comment by cal2195** [comment]
I just had a look - my uncompressed vha file is currently 1.7mb.

Rough calculations lead me to think that converting to objects would add about 2mb... (based on 200 characters added per file).

Do you think this is worth it?

**Comment by whyboris** [comment]
If a person is using this app, they're already committing to hundreds of megabytes taken up by screenshots, I don't think anyone would mind a 10mb _vha_ file 😅 

I'm certainly not opposed to zip compression -- it just looks like it might not be a super-quick change (catching errors, handling old files, and testing to make sure there are no edge cases we missed) -- only work on this if you're really eager about this feature, not if you think it's instrumental to converting .vha from an array of arrays to an array of objects 😅

**Comment by cal2195** [comment]
You have a good point - I'll leave it here for now, but we mightn't use it! 👍

**Comment by cal2195** [comment]
Update:

A sample .vha file with lots of files is `6mb` uncompressed with the new format.

Compressed, this file is `1.3mb` (80% reduction).

**Comment by cal2195** [comment]
@whyboris What are your current thoughts on zip compression?

**Comment by whyboris** [comment]
I'm not opposed to it if it's something you'd like to implement 👍 
Do let me know if you would like any assistance other than a PR review 👍

**Comment by whyboris** [comment]
Now that we're using `vha2` there's no conflict in having a completely different format than before (zipped _JSON_ rather than uncompressed _JSON_, that is). 

I still feel like compressing is added code complexity -- and saving hard drive space isn't important when the difference is 2MB vs 6MB. 

I'm thinking we either implement it before `2.0.0` or this feature would have to wait for `3.0.0` / if ever.

I'm leaning towards keeping things as is. @cal2195 -- please feel free to close the PR or let's discuss here whether we should get this feature in 👍 

In theory, there should only be 2 places where the new _zip_ code would be operating - when opening and when saving a file so it shouldn't be _too_ problematic ... but I rather like the hackability of the current file type (no need to unzip -- just open in notepad and hack away) 🤔

**Comment by whyboris** [comment]
I'm closing this as I'm cleaning up for version 2 release.

@cal2195 -- please comment if you'd like me to reopen (or reopen it yourself if you have the repository permission 👍 )

**Pull request closed without merging**
