### PR TITLE
Issue fixed: Off-by-one error in the number of clip snippets created

### PR DESCRIPTION
**Pull request by basavaraj96**
The issue has been fixed.

### CODE REVIEW

**Comment by whyboris** [comment]
🤝 Thank you! Code looks good -- I'll test it out sometime this weekend before merging 👍

**Comment by basavaraj96** [comment]
Hello... yes I was aware of the 'starting at 0' thing and was also a bit skeptical about committing it. But I assumed that it must be a bug and went ahead with the commit. If would like to fix it and create another pull request.

**Comment by basavaraj96** [comment]
I have made the necessary changes. Kindly review.

**Comment by whyboris** [comment]
🙇  Thank you very much! ❤

**Pull request merged**
