### PR TITLE
fix issue #757 - Folder size indicator show "k" when over 1,000

### PR DESCRIPTION
**Pull request by jmdagenais**
Will this PR count for Hacktoberfest?

### CODE REVIEW

**Review by whyboris — COMMENTED** [review]
Thank you very much for the contribution! 

Would you have time and interest in updating the code to use a `pipe` instead?

The main change would be to create a `pipe` (see other pipes I have to see how they work) - move the code you have from `component.ts` into the pipe, and finally use it in the template: `{{ video.fileSizeDisplay | kpipe }}` 🤔 

I gave a talk about _pipes_ if you'd like a quick intro: [YouTube](https://youtu.be/9cV_09a2Iyo?t=15176)

**Comment by whyboris** [comment]
This PR will close #769 👍

**Comment by jmdagenais** [comment]
Sure I will create a pipe.

**Comment by whyboris** [comment]
@jmdagenais looks awesome! Thank you for converting the code to a _pipe_ 🙇

**Review by whyboris — APPROVED** [review]
Code looks great! I'll try to merge it in this week 🤝  -- I just want to test it locally just in case 👍

**Pull request merged**
