### PR TITLE
Add sheet icon to thumbnails

### PR DESCRIPTION
**Pull request by cal2195**
This PR adds a sheet icon button to each thumbnail! Even I forget that `cmd+click` is a thing - this should help give the sheet view more use! 😄 

Let me know what you think! 👍

### CODE REVIEW

**Comment by whyboris** [comment]
Awesome feature!

Thank you again for continuously innovating 🙇 

Just let me know when you'd like me to review -- once you merge in _master_ it looks basically ready!

**Comment by whyboris** [comment]
Please pull in the latest _master_ as it's been updated 🙌

**Comment by cal2195** [comment]
Ready to go! 🚀

**Comment by whyboris** [comment]
Thank you for yet another sweet feature 🙌

**Pull request merged**
